config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'carts/:id' => 'carts#show', as: 'cart'
  delete 'carts/:id' => 'carts#destroy'

  post 'carts/sync' => 'carts#sync'
  post '/bills/sync' => 'bills#sync'

  get '/login' => 'user_session#new', :as => 'login'
  post '/login' => 'user_session#create'
  get '/logout' => 'user_session#destroy', :as => 'logout'

  resources :debts, :users, :bills

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Splittr</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="minimal-ui, width = device-width, initial-scale = 1.0, minimum-scale = 1, maximum-scale = 1, user-scalable = no"/>
    <meta name="apple-mobile-web-app-capable" content="yes"/>
    <meta name="mobile-web-app-capable" content="yes"/>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Bungee+Inline" rel="stylesheet">
    <%= favicon_link_tag 'Splittr.png', type: 'image/png' %>
    <%= favicon_link_tag 'Splittr.png', rel: 'apple-touch-icon' %>
  </head>
  <body>
    <header>
      <nav>
        <div class="container">
          <div class="row">
            <div class="col col-4">
              <span class="logo"><%= link_to 'Splittr', root_path %></span>
            </div>
            <div class="col col-8 right">
              <%= link_to 'Login', login_path unless @current_user %>
              <%= link_to @current_user.name,user_path(@current_user) if @current_user %>
            </div>
          </div>
        </div>
      </nav>
    </header>

    <div id="app">
      <%= yield %>
    </div>

  </body>
</html>